name: s3_deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "ap-northeast-1"
  AWS_ACCOUNTID: "471112601703"
  AWS_ROLENAME: "oidc-gh-role"
  AWS_S3_BUCKET: "okawak.net-bucket"
  SOURCE_DIR: "."

jobs:
  SyncS3:
    name: Upload the static files to AWS S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: arn:aws:iam::${{env.AWS_ACCOUNTID}}:role/${{env.AWS_ROLENAME}}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        if: success()
        working-directory: dist/okawak_net/browser
        run: aws s3 sync ${{env.SOURCE_DIR}} s3://${{env.AWS_S3_BUCKET}} --delete
